name = "ngunduhv2"
main = "worker.js"
compatibility_date = "2025-07-27"

[site]
bucket = "./public"

[build]
upload = { format = "modules" }

[[rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = false

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.txt"]